CREATE TABLE IF NOT EXISTS "location" (
  "id"            INT             PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name"          TEXT            UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "building" (
  "id"            INT             PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "location_id"   INT             NOT NULL REFERENCES "location" ("id"),
  "name"          TEXT            NOT NULL,
  UNIQUE(name, location_id)
);

CREATE TABLE IF NOT EXISTS "floor" (
  "id"            INT             PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "building_id"   INT             NOT NULL REFERENCES "building" ("id"),
  "mse_floor_id"  TEXT            UNIQUE NOT NULL,
  "name"          TEXT            NOT NULL,
  UNIQUE(name, building_id)
);

CREATE TABLE IF NOT EXISTS "client_count" (
  "time"          TIMESTAMPTZ     NOT NULL,
  "floor_id"      INT             NOT NULL REFERENCES "floor" ("id"),
  "auth_count"    INTEGER         ,
  "asso_count"    INTEGER         ,
  UNIQUE(time, floor_id)
);

CREATE TABLE IF NOT EXISTS "client_coordinate" (
  "floor_id"      INT             NOT NULL REFERENCES "floor" ("id"),
  "first_located" TIMESTAMPTZ     NOT NULL,
  "last_located"  TIMESTAMPTZ     NOT NULL,
  "cid"           TEXT            NOT NULL,
  "x"             NUMERIC(10, 4)  NOT NULL,
  "y"             NUMERIC(10, 4)  NOT NULL,
  UNIQUE (first_located, floor_id, cid, x, y)
);

CREATE INDEX IF NOT EXISTS idx_client_coordinate_last_located ON client_coordinate(last_located);

CREATE TABLE IF NOT EXISTS "floor_image" (
  "id"            INT             PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "floor_id"      INT             UNIQUE NOT NULL REFERENCES "floor" ("id"),
  "image_base64"  TEXT            ,
  "image_length"  NUMERIC(10, 6)  ,
  "image_width"   NUMERIC(10, 6)  ,
  "image_offsetX" NUMERIC(10, 6)  ,
  "image_offsetY" NUMERIC(10, 6)
);

SELECT create_hypertable('client_count', 'time', if_not_exists => TRUE);

SELECT create_hypertable('client_coordinate', 'first_located', if_not_exists => TRUE);

CREATE TYPE location_ids_names AS (
  "location_id" INT,
  "building_id" INT,
  "floor_id"    INT,
  "location"    TEXT,
  "building"    TEXT,
  "floor"       TEXT
);

CREATE FUNCTION get_id_from_names(
	location TEXT,
	building TEXT DEFAULT '',
	floor TEXT DEFAULT ''
) RETURNS location_ids_names AS $$
    SELECT
      l.id,
      b.id,
      f.id,
      l.name,
      b.name,
      f.name
      FROM (
        SELECT 
          l2.id,
          l2.name
        FROM location l2
        WHERE l2.name = location
      ) AS l
      LEFT JOIN building b
        ON
          b.location_id = l.id AND
          b.name = building
      LEFT JOIN floor f
        ON
          f.building_id = b.id AND
          f.name = floor
$$ LANGUAGE SQL;

CREATE FUNCTION get_names_from_floor_id (
	floor_id INT
) RETURNS location_ids_names AS $$
    SELECT
      l.id,
      b.id,
      f.id,
      l.name,
      b.name,
      f.name
	FROM floor f
	LEFT JOIN building b
	  ON f.building_id = b.id
	LEFT JOIN "location" l
	  ON b.location_id = l.id
	WHERE
	  f.id = floor_id;
$$ LANGUAGE SQL;
