version: "3.7"
services:
  chronograf:
    container_name: prime-chronograf
    image: chronograf
    command: ["--influxdb-url=http://influxdb:8086"]
    ports: 
      - 8888:8888
    networks:
      - influxdb
    depends_on:
      - influxdb

  influxdb:
    container_name: prime-influxdb
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - "./volumes/influxdb/db:/var/lib/influxdb"
    networks:
      - influxdb

networks:
  influxdb:
    external: false